name: Unit Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [12.x]
        package:
          - kakao_flutter_sdk_auth
          - kakao_flutter_sdk_common
          - kakao_flutter_sdk_share
          - kakao_flutter_sdk_story
          - kakao_flutter_sdk_talk
          - kakao_flutter_sdk_template
          - kakao_flutter_sdk_user
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version:  ${{ matrix.java-version }}

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Install dependencies
      working-directory: packages/${{ matrix.package }}
      run: flutter pub get
      
    #   There are currently many analysis errors in the SDK. We should fix them.
    # - name: Analyze
    #   working-directory: packages/${{ matrix.package }}
    #   run: dart analyze . --fatal-infos

    - run: flutter test test/
      working-directory: packages/${{ matrix.package }}